name: toor
description: A starting point for Dart libraries or applications.
version: 1.0.0

homepage: https://github.com/f-person/toor
repository: https://github.com/f-person/toor
issue_tracker: https://github.com/f-person/toor/issues

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  meta: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  vm_service: ^8.3.0
